package de.niklasbednarczyk.nbdex.core.ui.designsystem.theme.color.extended.type

import androidx.compose.ui.graphics.Color

// Source color #91A119 from https://bulbapedia.bulbagarden.net/wiki/Template:Bug_color
internal val typeBugLightStandardContrast = Color(0xFF91A119)
internal val onTypeBugLightStandardContrast = Color(0xFF2E3400)
internal val typeBugLightMediumContrast = Color(0xFF677400)
internal val onTypeBugLightMediumContrast = Color(0xFFFFFFFF)
internal val typeBugLightHighContrast = Color(0xFF454E00)
internal val onTypeBugLightHighContrast = Color(0xFFFFFFFF)
internal val typeBugDarkStandardContrast = Color(0xFF91A119)
internal val onTypeBugDarkStandardContrast = Color(0xFF2E3400)
internal val typeBugDarkMediumContrast = Color(0xFF91A119)
internal val onTypeBugDarkMediumContrast = Color(0xFF050700)
internal val typeBugDarkHighContrast = Color(0xFFBBCC45)
internal val onTypeBugDarkHighContrast = Color(0xFF0A0D00)

// Source color #624D4E from https://bulbapedia.bulbagarden.net/wiki/Template:Dark_color
internal val typeDarkLightStandardContrast = Color(0xFF624D4E)
internal val onTypeDarkLightStandardContrast = Color(0xFFDBBFC0)
internal val typeDarkLightMediumContrast = Color(0xFF624D4E)
internal val onTypeDarkLightMediumContrast = Color(0xFFFFF0F0)
internal val typeDarkLightHighContrast = Color(0xFF584445)
internal val onTypeDarkLightHighContrast = Color(0xFFFFFFFF)
internal val typeDarkDarkStandardContrast = Color(0xFF624D4E)
internal val onTypeDarkDarkStandardContrast = Color(0xFFDBBFC0)
internal val typeDarkDarkMediumContrast = Color(0xFFA48B8C)
internal val onTypeDarkDarkMediumContrast = Color(0xFF000000)
internal val typeDarkDarkHighContrast = Color(0xFFD8BCBD)
internal val onTypeDarkDarkHighContrast = Color(0xFF150709)

// Source color #5060E1 from https://bulbapedia.bulbagarden.net/wiki/Template:Dragon_color
internal val typeDragonLightStandardContrast = Color(0xFF5060E1)
internal val onTypeDragonLightStandardContrast = Color(0xFFF1F0FF)
internal val typeDragonLightMediumContrast = Color(0xFF5060E1)
internal val onTypeDragonLightMediumContrast = Color(0xFFFFFFFF)
internal val typeDragonLightHighContrast = Color(0xFF2637BB)
internal val onTypeDragonLightHighContrast = Color(0xFFFFFFFF)
internal val typeDragonDarkStandardContrast = Color(0xFF5060E1)
internal val onTypeDragonDarkStandardContrast = Color(0xFFF1F0FF)
internal val typeDragonDarkMediumContrast = Color(0xFF7786FF)
internal val onTypeDragonDarkMediumContrast = Color(0xFF000000)
internal val typeDragonDarkHighContrast = Color(0xFFB8BEFF)
internal val onTypeDragonDarkHighContrast = Color(0xFF000337)

// Source color #FAC000 from https://bulbapedia.bulbagarden.net/wiki/Template:Electric_color
internal val typeElectricLightStandardContrast = Color(0xFFFAC000)
internal val onTypeElectricLightStandardContrast = Color(0xFF6A5000)
internal val typeElectricLightMediumContrast = Color(0xFF896800)
internal val onTypeElectricLightMediumContrast = Color(0xFFFFFFFF)
internal val typeElectricLightHighContrast = Color(0xFF5D4600)
internal val onTypeElectricLightHighContrast = Color(0xFFFFFFFF)
internal val typeElectricDarkStandardContrast = Color(0xFFFAC000)
internal val onTypeElectricDarkStandardContrast = Color(0xFF6A5000)
internal val typeElectricDarkMediumContrast = Color(0xFFFAC000)
internal val onTypeElectricDarkMediumContrast = Color(0xFF473500)
internal val typeElectricDarkHighContrast = Color(0xFFFAC000)
internal val onTypeElectricDarkHighContrast = Color(0xFF1B1200)

// Source color #EF70EF from https://bulbapedia.bulbagarden.net/wiki/Template:Fairy_color
internal val typeFairyLightStandardContrast = Color(0xFFEF70EF)
internal val onTypeFairyLightStandardContrast = Color(0xFF68006D)
internal val typeFairyLightMediumContrast = Color(0xFFB036B4)
internal val onTypeFairyLightMediumContrast = Color(0xFFFFFFFF)
internal val typeFairyLightHighContrast = Color(0xFF83008A)
internal val onTypeFairyLightHighContrast = Color(0xFFFFFFFF)
internal val typeFairyDarkStandardContrast = Color(0xFFEF70EF)
internal val onTypeFairyDarkStandardContrast = Color(0xFF68006D)
internal val typeFairyDarkMediumContrast = Color(0xFFEF70EF)
internal val onTypeFairyDarkMediumContrast = Color(0xFF2F0032)
internal val typeFairyDarkHighContrast = Color(0xFFFFA3FA)
internal val onTypeFairyDarkHighContrast = Color(0xFF1C001E)

// Source color #FF8000 from https://bulbapedia.bulbagarden.net/wiki/Template:Fighting_color
internal val typeFightingLightStandardContrast = Color(0xFFFF8000)
internal val onTypeFightingLightStandardContrast = Color(0xFF5E2B00)
internal val typeFightingLightMediumContrast = Color(0xFFAC5500)
internal val onTypeFightingLightMediumContrast = Color(0xFFFFFFFF)
internal val typeFightingLightHighContrast = Color(0xFF763800)
internal val onTypeFightingLightHighContrast = Color(0xFFFFFFFF)
internal val typeFightingDarkStandardContrast = Color(0xFFFF8000)
internal val onTypeFightingDarkStandardContrast = Color(0xFF5E2B00)
internal val typeFightingDarkMediumContrast = Color(0xFFFF8000)
internal val onTypeFightingDarkMediumContrast = Color(0xFF2C1100)
internal val typeFightingDarkHighContrast = Color(0xFFFFB17D)
internal val onTypeFightingDarkHighContrast = Color(0xFF180700)

// Source color #E62829 from https://bulbapedia.bulbagarden.net/wiki/Template:Fire_color
internal val typeFireLightStandardContrast = Color(0xFFE22527)
internal val onTypeFireLightStandardContrast = Color(0xFFFFFBFF)
internal val typeFireLightMediumContrast = Color(0xFFD71A20)
internal val onTypeFireLightMediumContrast = Color(0xFFFFFFFF)
internal val typeFireLightHighContrast = Color(0xFF98000D)
internal val onTypeFireLightHighContrast = Color(0xFFFFFFFF)
internal val typeFireDarkStandardContrast = Color(0xFFFF544B)
internal val onTypeFireDarkStandardContrast = Color(0xFF170000)
internal val typeFireDarkMediumContrast = Color(0xFFFF544B)
internal val onTypeFireDarkMediumContrast = Color(0xFF000000)
internal val typeFireDarkHighContrast = Color(0xFFFFAEA5)
internal val onTypeFireDarkHighContrast = Color(0xFF170000)

// Source color #81B9EF from https://bulbapedia.bulbagarden.net/wiki/Template:Flying_color
internal val typeFlyingLightStandardContrast = Color(0xFF81B9EF)
internal val onTypeFlyingLightStandardContrast = Color(0xFF004975)
internal val typeFlyingLightMediumContrast = Color(0xFF3571A3)
internal val onTypeFlyingLightMediumContrast = Color(0xFFFFFFFF)
internal val typeFlyingLightHighContrast = Color(0xFF004D7A)
internal val onTypeFlyingLightHighContrast = Color(0xFFFFFFFF)
internal val typeFlyingDarkStandardContrast = Color(0xFF81B9EF)
internal val onTypeFlyingDarkStandardContrast = Color(0xFF004975)
internal val typeFlyingDarkMediumContrast = Color(0xFF81B9EF)
internal val onTypeFlyingDarkMediumContrast = Color(0xFF002B47)
internal val typeFlyingDarkHighContrast = Color(0xFF90C8FE)
internal val onTypeFlyingDarkHighContrast = Color(0xFF000C19)

// Source color #704170 from https://bulbapedia.bulbagarden.net/wiki/Template:Ghost_color
internal val typeGhostLightStandardContrast = Color(0xFF704170)
internal val onTypeGhostLightStandardContrast = Color(0xFFEDB3E9)
internal val typeGhostLightMediumContrast = Color(0xFF704170)
internal val onTypeGhostLightMediumContrast = Color(0xFFFFEFF9)
internal val typeGhostLightHighContrast = Color(0xFF663867)
internal val onTypeGhostLightHighContrast = Color(0xFFFFFFFF)
internal val typeGhostDarkStandardContrast = Color(0xFF704170)
internal val onTypeGhostDarkStandardContrast = Color(0xFFEDB3E9)
internal val typeGhostDarkMediumContrast = Color(0xFFB57FB2)
internal val onTypeGhostDarkMediumContrast = Color(0xFF000000)
internal val typeGhostDarkHighContrast = Color(0xFFEAB0E6)
internal val onTypeGhostDarkHighContrast = Color(0xFF1C001F)

// Source color #3FA129 from https://bulbapedia.bulbagarden.net/wiki/Template:Grass_color
internal val typeGrassLightStandardContrast = Color(0xFF22870B)
internal val onTypeGrassLightStandardContrast = Color(0xFFF8FFEF)
internal val typeGrassLightMediumContrast = Color(0xFF177F00)
internal val onTypeGrassLightMediumContrast = Color(0xFFFFFFFF)
internal val typeGrassLightHighContrast = Color(0xFF0D5600)
internal val onTypeGrassLightHighContrast = Color(0xFFFFFFFF)
internal val typeGrassDarkStandardContrast = Color(0xFF43A52C)
internal val onTypeGrassDarkStandardContrast = Color(0xFF042E00)
internal val typeGrassDarkMediumContrast = Color(0xFF43A52C)
internal val onTypeGrassDarkMediumContrast = Color(0xFF000000)
internal val typeGrassDarkHighContrast = Color(0xFF75D95B)
internal val onTypeGrassDarkHighContrast = Color(0xFF010F00)

// Source color #915121 from https://bulbapedia.bulbagarden.net/wiki/Template:Ground_color
internal val typeGroundLightStandardContrast = Color(0xFF915121)
internal val onTypeGroundLightStandardContrast = Color(0xFFFFD5BC)
internal val typeGroundLightMediumContrast = Color(0xFF915121)
internal val onTypeGroundLightMediumContrast = Color(0xFFFFFFFF)
internal val typeGroundLightHighContrast = Color(0xFF733A0A)
internal val onTypeGroundLightHighContrast = Color(0xFFFFFFFF)
internal val typeGroundDarkStandardContrast = Color(0xFF915121)
internal val onTypeGroundDarkStandardContrast = Color(0xFFFFD5BC)
internal val typeGroundDarkMediumContrast = Color(0xFFC97F4B)
internal val onTypeGroundDarkMediumContrast = Color(0xFF000000)
internal val typeGroundDarkHighContrast = Color(0xFFFFB17D)
internal val onTypeGroundDarkHighContrast = Color(0xFF180700)

// Source color #3DCEF3 from https://bulbapedia.bulbagarden.net/wiki/Template:Ice_color
internal val typeIceLightStandardContrast = Color(0xFF3DCEF3)
internal val onTypeIceLightStandardContrast = Color(0xFF005567)
internal val typeIceLightMediumContrast = Color(0xFF007790)
internal val onTypeIceLightMediumContrast = Color(0xFFFFFFFF)
internal val typeIceLightHighContrast = Color(0xFF005062)
internal val onTypeIceLightHighContrast = Color(0xFFFFFFFF)
internal val typeIceDarkStandardContrast = Color(0xFF3DCEF3)
internal val onTypeIceDarkStandardContrast = Color(0xFF005567)
internal val typeIceDarkMediumContrast = Color(0xFF3DCEF3)
internal val onTypeIceDarkMediumContrast = Color(0xFF003642)
internal val typeIceDarkHighContrast = Color(0xFF44D2F7)
internal val onTypeIceDarkHighContrast = Color(0xFF000D12)

// Source color #9FA19F from https://bulbapedia.bulbagarden.net/wiki/Template:Normal_color
internal val typeNormalLightStandardContrast = Color(0xFF9FA19F)
internal val onTypeNormalLightStandardContrast = Color(0xFF353837)
internal val typeNormalLightMediumContrast = Color(0xFF6B6E6C)
internal val onTypeNormalLightMediumContrast = Color(0xFFFFFFFF)
internal val typeNormalLightHighContrast = Color(0xFF474A48)
internal val onTypeNormalLightHighContrast = Color(0xFFFFFFFF)
internal val typeNormalDarkStandardContrast = Color(0xFF9FA19F)
internal val onTypeNormalDarkStandardContrast = Color(0xFF353837)
internal val typeNormalDarkMediumContrast = Color(0xFF9FA19F)
internal val onTypeNormalDarkMediumContrast = Color(0xFF121514)
internal val typeNormalDarkHighContrast = Color(0xFFC1C3C1)
internal val onTypeNormalDarkHighContrast = Color(0xFF090C0B)

// Source color #9141CB from https://bulbapedia.bulbagarden.net/wiki/Template:Poison_color
internal val typePoisonLightStandardContrast = Color(0xFF9141CB)
internal val onTypePoisonLightStandardContrast = Color(0xFFF7E3FF)
internal val typePoisonLightMediumContrast = Color(0xFF9141CB)
internal val onTypePoisonLightMediumContrast = Color(0xFFFFFFFF)
internal val typePoisonLightHighContrast = Color(0xFF6E15A8)
internal val onTypePoisonLightHighContrast = Color(0xFFFFFFFF)
internal val typePoisonDarkStandardContrast = Color(0xFF9141CB)
internal val onTypePoisonDarkStandardContrast = Color(0xFFF7E3FF)
internal val typePoisonDarkMediumContrast = Color(0xFFBC6CF7)
internal val onTypePoisonDarkMediumContrast = Color(0xFF000000)
internal val typePoisonDarkHighContrast = Color(0xFFE0B0FF)
internal val onTypePoisonDarkHighContrast = Color(0xFF170029)

// Source color #EF4179 from https://bulbapedia.bulbagarden.net/wiki/Template:Psychic_color
internal val typePsychicLightStandardContrast = Color(0xFFD82E69)
internal val onTypePsychicLightStandardContrast = Color(0xFFFFFBFF)
internal val typePsychicLightMediumContrast = Color(0xFFCE2561)
internal val onTypePsychicLightMediumContrast = Color(0xFFFFFFFF)
internal val typePsychicLightHighContrast = Color(0xFF940040)
internal val onTypePsychicLightHighContrast = Color(0xFFFFFFFF)
internal val typePsychicDarkStandardContrast = Color(0xFFFE4D84)
internal val onTypePsychicDarkStandardContrast = Color(0xFF430019)
internal val typePsychicDarkMediumContrast = Color(0xFFFE4D84)
internal val onTypePsychicDarkMediumContrast = Color(0xFF000000)
internal val typePsychicDarkHighContrast = Color(0xFFFFABBC)
internal val onTypePsychicDarkHighContrast = Color(0xFF210009)

// Source color #AFA981 from https://bulbapedia.bulbagarden.net/wiki/Template:Rock_color
internal val typeRockLightStandardContrast = Color(0xFFAFA981)
internal val onTypeRockLightStandardContrast = Color(0xFF413E1F)
internal val typeRockLightMediumContrast = Color(0xFF736E4A)
internal val onTypeRockLightMediumContrast = Color(0xFFFFFFFF)
internal val typeRockLightHighContrast = Color(0xFF4E4A2A)
internal val onTypeRockLightHighContrast = Color(0xFFFFFFFF)
internal val typeRockDarkStandardContrast = Color(0xFFAFA981)
internal val onTypeRockDarkStandardContrast = Color(0xFF413E1F)
internal val typeRockDarkMediumContrast = Color(0xFFAFA981)
internal val onTypeRockDarkMediumContrast = Color(0xFF211E03)
internal val typeRockDarkHighContrast = Color(0xFFCAC49A)
internal val onTypeRockDarkHighContrast = Color(0xFF0D0B00)

// Source color #604E82 from https://bulbapedia.bulbagarden.net/wiki/Template:XD_color
internal val typeShadowLightStandardContrast = Color(0xFF604E82)
internal val onTypeShadowLightStandardContrast = Color(0xFFD9C3FF)
internal val typeShadowLightMediumContrast = Color(0xFF604E82)
internal val onTypeShadowLightMediumContrast = Color(0xFFFFFCFF)
internal val typeShadowLightHighContrast = Color(0xFF524073)
internal val onTypeShadowLightHighContrast = Color(0xFFFFFFFF)
internal val typeShadowDarkStandardContrast = Color(0xFF604E82)
internal val onTypeShadowDarkStandardContrast = Color(0xFFD9C3FF)
internal val typeShadowDarkMediumContrast = Color(0xFF9B87BF)
internal val onTypeShadowDarkMediumContrast = Color(0xFF000000)
internal val typeShadowDarkHighContrast = Color(0xFFCEB9F4)
internal val onTypeShadowDarkHighContrast = Color(0xFF110030)

// Source color #60A1B8 from https://bulbapedia.bulbagarden.net/wiki/Template:Steel_color
internal val typeSteelLightStandardContrast = Color(0xFF60A1B8)
internal val onTypeSteelLightStandardContrast = Color(0xFF003543)
internal val typeSteelLightMediumContrast = Color(0xFF31758B)
internal val onTypeSteelLightMediumContrast = Color(0xFFFFFFFF)
internal val typeSteelLightHighContrast = Color(0xFF005063)
internal val onTypeSteelLightHighContrast = Color(0xFFFFFFFF)
internal val typeSteelDarkStandardContrast = Color(0xFF60A1B8)
internal val onTypeSteelDarkStandardContrast = Color(0xFF003543)
internal val typeSteelDarkMediumContrast = Color(0xFF60A1B8)
internal val onTypeSteelDarkMediumContrast = Color(0xFF00060A)
internal val typeSteelDarkHighContrast = Color(0xFF8BCCE4)
internal val onTypeSteelDarkHighContrast = Color(0xFF000D13)

// Source color #40B5A5 from https://bulbapedia.bulbagarden.net/wiki/Template:Stellar_color
internal val typeStellarLightStandardContrast = Color(0xFF40B5A5)
internal val onTypeStellarLightStandardContrast = Color(0xFF00423A)
internal val typeStellarLightMediumContrast = Color(0xFF007B6E)
internal val onTypeStellarLightMediumContrast = Color(0xFFFFFFFF)
internal val typeStellarLightHighContrast = Color(0xFF00534A)
internal val onTypeStellarLightHighContrast = Color(0xFFFFFFFF)
internal val typeStellarDarkStandardContrast = Color(0xFF40B5A5)
internal val onTypeStellarDarkStandardContrast = Color(0xFF00423A)
internal val typeStellarDarkMediumContrast = Color(0xFF40B5A5)
internal val onTypeStellarDarkMediumContrast = Color(0xFF001D19)
internal val typeStellarDarkHighContrast = Color(0xFF64D5C4)
internal val onTypeStellarDarkHighContrast = Color(0xFF000E0B)

// Source color #68A090 from https://bulbapedia.bulbagarden.net/wiki/Template:Unknown_color
internal val typeUnknownLightStandardContrast = Color(0xFF68A090)
internal val onTypeUnknownLightStandardContrast = Color(0xFF00352B)
internal val typeUnknownLightMediumContrast = Color(0xFF3F7768)
internal val onTypeUnknownLightMediumContrast = Color(0xFFFFFFFF)
internal val typeUnknownLightHighContrast = Color(0xFF175245)
internal val onTypeUnknownLightHighContrast = Color(0xFFFFFFFF)
internal val typeUnknownDarkStandardContrast = Color(0xFF68A090)
internal val onTypeUnknownDarkStandardContrast = Color(0xFF00352B)
internal val typeUnknownDarkMediumContrast = Color(0xFF68A090)
internal val onTypeUnknownDarkMediumContrast = Color(0xFF000000)
internal val typeUnknownDarkHighContrast = Color(0xFF95CEBD)
internal val onTypeUnknownDarkHighContrast = Color(0xFF000E0A)

// Source color #2980EF from https://bulbapedia.bulbagarden.net/wiki/Template:Water_color
internal val typeWaterLightStandardContrast = Color(0xFF0872E1)
internal val onTypeWaterLightStandardContrast = Color(0xFFFEFCFF)
internal val typeWaterLightMediumContrast = Color(0xFF006BD4)
internal val onTypeWaterLightMediumContrast = Color(0xFFFFFFFF)
internal val typeWaterLightHighContrast = Color(0xFF004892)
internal val onTypeWaterLightHighContrast = Color(0xFFFFFFFF)
internal val typeWaterDarkStandardContrast = Color(0xFF4090FF)
internal val onTypeWaterDarkStandardContrast = Color(0xFF00193A)
internal val typeWaterDarkMediumContrast = Color(0xFF4090FF)
internal val onTypeWaterDarkMediumContrast = Color(0xFF000000)
internal val typeWaterDarkHighContrast = Color(0xFFA4C3FF)
internal val onTypeWaterDarkHighContrast = Color(0xFF000B20)
