config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: true
processors:
  active: true
console-reports:
  active: true
  exclude:
  - ProjectStatisticsReport
  - ComplexityReport
  - NotificationReport
  - IssuesReport
  - FileBasedIssuesReport
comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
  DeprecatedBlockTag:
    active: false
  DocumentationOverPrivateFunction:
    active: false
  DocumentationOverPrivateProperty:
    active: false
  EndOfSentenceFormat:
    active: false
  KDocReferencesNonPublicProperty:
    active: false
  OutdatedDocumentation:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: true
    excludes:
    - src/**
    includes:
    - '**/core/model/id/Core**'
    - '**/core/ui/designsystem/theme/color/extended/**/**'
    - '**/core/ui/designsystem/theme/dimension/**/**'
    - '**/core/ui/designsystem/theme/dimension/NBDimensionsPadding.kt'
complexity:
  active: true
  CognitiveComplexMethod:
    active: true
  ComplexCondition:
    active: true
  ComplexInterface:
    active: true
  CyclomaticComplexMethod:
    active: false
  LabeledExpression:
    active: true
  LargeClass:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: true
  MethodOverloading:
    active: true
  NamedArguments:
    active: true
    excludes:
    - '**/core/ui/resource/icon/**'
    allowedArguments: 1
    ignoreMethods:
    - androidx.compose.runtime.remember
    - kotlin.Pair.<init>
    - kotlin.Triple.<init>
    - kotlin.comparisons.compareValuesBy
    - kotlin.comparisons.maxOf
    - kotlinx.coroutines.flow.combine
  NestedBlockDepth:
    active: true
  NestedScopeFunctions:
    active: true
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: false
  TooManyFunctions:
    active: false
coroutines:
  active: true
  CoroutineLaunchedInTestWithoutRunTest:
    active: true
  GlobalCoroutineUsage:
    active: true
  InjectDispatcher:
    active: true
    excludes:
    - '**/core/common/dispatchers/**'
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunInFinallySection:
    active: true
  SuspendFunSwallowedCancellation:
    active: true
  SuspendFunWithCoroutineScopeReceiver:
    active: true
  SuspendFunWithFlowReturnType:
    active: true
empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKotlinFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true
exceptions:
  active: true
  ErrorUsageWithThrowable:
    active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
  InstanceOfCheckForException:
    active: true
  NotImplementedDeclaration:
    active: true
  ObjectExtendsThrowable:
    active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: true
  TooGenericExceptionThrown:
    active: true
naming:
  active: true
  BooleanPropertyNaming:
    active: true
    excludes:
    - '**/core/model/endpoint/**'
    - '**/core/persistence/model/**'
    allowedPattern: ^(is|has|are|selected|expanded|show)
  ClassNaming:
    active: true
  ConstructorParameterNaming:
    active: true
  EnumNaming:
    active: true
  ForbiddenClassName:
    active: true
  FunctionNameMaxLength:
    active: false
  FunctionNameMinLength:
    active: true
  FunctionNaming:
    active: true
    ignoreAnnotated:
    - Composable
  FunctionParameterNaming:
    active: true
  InvalidPackageDeclaration:
    active: true
  LambdaParameterNaming:
    active: true
  MatchingDeclarationName:
    active: true
  MemberNameEqualsClassName:
    active: true
  NoNameShadowing:
    active: true
    excludes:
    - '**/core/model/endpoint/display/model/**'
  NonBooleanPropertyPrefixedWithIs:
    active: true
  ObjectPropertyNaming:
    active: true
  PackageNaming:
    active: true
  TopLevelPropertyNaming:
    active: true
  VariableMaxLength:
    active: true
  VariableMinLength:
    active: true
  VariableNaming:
    active: true
performance:
  active: true
  ArrayPrimitive:
    active: true
  CouldBeSequence:
    active: true
    allowedOperations: 1
  ForEachOnRange:
    active: true
  SpreadOperator:
    active: true
  UnnecessaryInitOnArray:
    active: true
  UnnecessaryPartOfBinaryExpression:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true
  UnnecessaryTypeCasting:
    active: true
potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: true
  CastNullableToNonNullableType:
    active: true
  CastToNullableType:
    active: true
  CharArrayToStringCall:
    active: true
  Deprecation:
    active: true
  DontDowncastCollectionTypes:
    active: true
  DoubleMutabilityForCollection:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExitOutsideMain:
    active: true
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: true
  IgnoredReturnValue:
    active: true
  ImplicitDefaultLocale:
    active: true
  ImplicitUnitReturnType:
    active: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingPackageDeclaration:
    active: true
  MissingSuperCall:
    active: true
  MissingUseCall:
    active: false
  NullCheckOnMutableProperty:
    active: true
  NullableToStringCall:
    active: true
  PropertyUsedBeforeDeclaration:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnamedParameterUse:
    active: false
  UnnecessaryNotNullCheck:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCatchBlock:
    active: true
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
    excludes:
    - '**/core/ui/resource/icon/**'
  UnsafeCast:
    active: true
  UnusedUnaryOperator:
    active: true
  UselessPostfixExpression:
    active: true
  WrongEqualsTypeParameter:
    active: true
style:
  active: true
  AbstractClassCanBeConcreteClass:
    active: true
  AbstractClassCanBeInterface:
    active: true
  AlsoCouldBeApply:
    active: true
  BracesOnIfStatements:
    active: true
  BracesOnWhenStatements:
    active: true
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  DataClassShouldBeImmutable:
    active: true
  DestructuringDeclarationWithTooManyEntries:
    active: true
  DoubleNegativeExpression:
    active: true
  DoubleNegativeLambda:
    active: true
  EqualsNullCall:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExplicitItLambdaMultipleParameters:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ExpressionBodySyntax:
    active: false
  ForbiddenAnnotation:
    active: true
  ForbiddenComment:
    active: true
  ForbiddenImport:
    active: true
  ForbiddenMethodCall:
    active: true
  ForbiddenNamedParam:
    active: true
    methods:
    - org.jetbrains.compose.resources.stringResource
  ForbiddenOptIn:
    active: true
  ForbiddenSuppress:
    active: true
  ForbiddenVoid:
    active: true
  FunctionOnlyReturningConstant:
    active: true
  LoopWithTooManyJumpStatements:
    active: true
  MagicNumber:
    active: true
  MandatoryBracesLoops:
    active: true
  MaxChainedCallsOnSameLine:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  MayBeConstant:
    active: true
  ModifierOrder:
    active: true
  MultilineLambdaItParameter:
    active: true
  MultilineRawStringIndentation:
    active: true
  NestedClassesVisibility:
    active: true
  NewLineAtEndOfFile:
    active: true
  NoTabs:
    active: true
  NullableBooleanCheck:
    active: true
  ObjectLiteralToLambda:
    active: true
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: true
  ProtectedMemberInFinalClass:
    active: true
  RangeUntilInsteadOfRangeTo:
    active: true
  RedundantConstructorKeyword:
    active: true
  RedundantExplicitType:
    active: true
  RedundantHigherOrderMapUsage:
    active: true
  RedundantVisibilityModifier:
    active: true
  ReturnCount:
    active: true
    max: 1
    excludeGuardClauses: true
  SafeCast:
    active: true
  SerialVersionUIDInSerializableClass:
    active: true
  SpacingAfterPackageAndImports:
    active: true
  StringShouldBeRawString:
    active: true
  ThrowsCount:
    active: true
  TrailingWhitespace:
    active: true
  TrimMultilineRawString:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryAny:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryBackticks:
    active: true
  UnnecessaryBracesAroundTrailingLambda:
    active: true
  UnnecessaryFilter:
    active: true
  UnnecessaryFullyQualifiedName:
    active: true
  UnnecessaryInheritance:
    active: true
  UnnecessaryInnerClass:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UnnecessaryReversed:
    active: true
  UnusedImport:
    active: true
  UnusedParameter:
    active: true
  UnusedPrivateClass:
    active: true
  UnusedPrivateFunction:
    active: true
    ignoreAnnotated:
    - Preview
  UnusedPrivateProperty:
    active: true
  UnusedVariable:
    active: true
  UseAnyOrNoneInsteadOfFind:
    active: true
  UseArrayLiteralsInAnnotations:
    active: true
  UseCheckNotNull:
    active: true
  UseCheckOrError:
    active: true
  UseDataClass:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseIsNullOrEmpty:
    active: true
  UseLet:
    active: true
  UseOrEmpty:
    active: true
  UseRequire:
    active: true
  UseRequireNotNull:
    active: true
  UseSumOfInsteadOfFlatMapSize:
    active: true
  UselessCallOnNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: true
Compose:
  ComposableAnnotationNaming:
    active: true
  ComposableNaming:
    active: true
  ComposableNestingDepth:
    active: true
  ComposableParamOrder:
    active: true
  CompositionLocalAllowlist:
    active: true
    allowedCompositionLocals:
    - LocalNBDimensions
    - LocalNBExtendedColors
    - LocalNBIsDarkTheme
    - LocalNBIsSinglePane
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
  ContentTrailingLambda:
    active: true
  ContentSlotReused:
    active: true
  DefaultsVisibility:
    active: true
  InvalidReadOnlyComposable:
    active: true
  LambdaParameterEventTrailing:
    active: true
  LambdaParameterInRestartableEffect:
    active: true
  Material2:
    active: true
  MissingNonRestartableComposable:
    active: true
  MissingReadOnlyComposable:
    active: true
  ModifierClickableOrder:
    active: true
  ModifierComposed:
    active: true
  ModifierMissing:
    active: true
    checkModifiersForVisibility: all
  ModifierNaming:
    active: true
  ModifierNotUsedAtRoot:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
  MutableParams:
    active: true
  MutableStateAutoboxing:
    active: true
  MutableStateParam:
    active: true
  ParameterNaming:
    active: true
  PreviewAnnotationNaming:
    active: true
  PreviewNaming:
    active: true
  PreviewPublic:
    active: true
  RememberContentMissing:
    active: true
  RememberMissing:
    active: true
  StaleRememberUpdatedStateInRemember:
    active: true
  StateParam:
    active: true
  UnnecessaryComposable:
    active: true
  UnnecessaryLaunchedEffect:
    active: true
  UnstableCollections:
    active: true
  VarsWithoutStateBacking:
    active: true
  ViewModelForwarding:
    active: true
  ViewModelInjection:
    active: true
