package de.niklasbednarczyk.nbdex.core.ui.designsystem.theme.color.scheme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import de.niklasbednarczyk.nbdex.core.model.settings.CoreSettingsContrast

private val lightStandardContrastColorScheme = lightColorScheme(
    primary = primaryLightStandardContrast,
    onPrimary = onPrimaryLightStandardContrast,
    primaryContainer = primaryContainerLightStandardContrast,
    onPrimaryContainer = onPrimaryContainerLightStandardContrast,
    secondary = secondaryLightStandardContrast,
    onSecondary = onSecondaryLightStandardContrast,
    secondaryContainer = secondaryContainerLightStandardContrast,
    onSecondaryContainer = onSecondaryContainerLightStandardContrast,
    tertiary = tertiaryLightStandardContrast,
    onTertiary = onTertiaryLightStandardContrast,
    tertiaryContainer = tertiaryContainerLightStandardContrast,
    onTertiaryContainer = onTertiaryContainerLightStandardContrast,
    error = errorLightStandardContrast,
    onError = onErrorLightStandardContrast,
    errorContainer = errorContainerLightStandardContrast,
    onErrorContainer = onErrorContainerLightStandardContrast,
    background = backgroundLightStandardContrast,
    onBackground = onBackgroundLightStandardContrast,
    surface = surfaceLightStandardContrast,
    onSurface = onSurfaceLightStandardContrast,
    surfaceVariant = surfaceVariantLightStandardContrast,
    onSurfaceVariant = onSurfaceVariantLightStandardContrast,
    outline = outlineLightStandardContrast,
    outlineVariant = outlineVariantLightStandardContrast,
    scrim = scrimLightStandardContrast,
    inverseSurface = inverseSurfaceLightStandardContrast,
    inverseOnSurface = inverseOnSurfaceLightStandardContrast,
    inversePrimary = inversePrimaryLightStandardContrast,
    surfaceDim = surfaceDimLightStandardContrast,
    surfaceBright = surfaceBrightLightStandardContrast,
    surfaceContainerLowest = surfaceContainerLowestLightStandardContrast,
    surfaceContainerLow = surfaceContainerLowLightStandardContrast,
    surfaceContainer = surfaceContainerLightStandardContrast,
    surfaceContainerHigh = surfaceContainerHighLightStandardContrast,
    surfaceContainerHighest = surfaceContainerHighestLightStandardContrast,
)

private val lightMediumContrastColorScheme = lightColorScheme(
    primary = primaryLightMediumContrast,
    onPrimary = onPrimaryLightMediumContrast,
    primaryContainer = primaryContainerLightMediumContrast,
    onPrimaryContainer = onPrimaryContainerLightMediumContrast,
    secondary = secondaryLightMediumContrast,
    onSecondary = onSecondaryLightMediumContrast,
    secondaryContainer = secondaryContainerLightMediumContrast,
    onSecondaryContainer = onSecondaryContainerLightMediumContrast,
    tertiary = tertiaryLightMediumContrast,
    onTertiary = onTertiaryLightMediumContrast,
    tertiaryContainer = tertiaryContainerLightMediumContrast,
    onTertiaryContainer = onTertiaryContainerLightMediumContrast,
    error = errorLightMediumContrast,
    onError = onErrorLightMediumContrast,
    errorContainer = errorContainerLightMediumContrast,
    onErrorContainer = onErrorContainerLightMediumContrast,
    background = backgroundLightMediumContrast,
    onBackground = onBackgroundLightMediumContrast,
    surface = surfaceLightMediumContrast,
    onSurface = onSurfaceLightMediumContrast,
    surfaceVariant = surfaceVariantLightMediumContrast,
    onSurfaceVariant = onSurfaceVariantLightMediumContrast,
    outline = outlineLightMediumContrast,
    outlineVariant = outlineVariantLightMediumContrast,
    scrim = scrimLightMediumContrast,
    inverseSurface = inverseSurfaceLightMediumContrast,
    inverseOnSurface = inverseOnSurfaceLightMediumContrast,
    inversePrimary = inversePrimaryLightMediumContrast,
    surfaceDim = surfaceDimLightMediumContrast,
    surfaceBright = surfaceBrightLightMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = surfaceContainerLowLightMediumContrast,
    surfaceContainer = surfaceContainerLightMediumContrast,
    surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
)

private val lightHighContrastColorScheme = lightColorScheme(
    primary = primaryLightHighContrast,
    onPrimary = onPrimaryLightHighContrast,
    primaryContainer = primaryContainerLightHighContrast,
    onPrimaryContainer = onPrimaryContainerLightHighContrast,
    secondary = secondaryLightHighContrast,
    onSecondary = onSecondaryLightHighContrast,
    secondaryContainer = secondaryContainerLightHighContrast,
    onSecondaryContainer = onSecondaryContainerLightHighContrast,
    tertiary = tertiaryLightHighContrast,
    onTertiary = onTertiaryLightHighContrast,
    tertiaryContainer = tertiaryContainerLightHighContrast,
    onTertiaryContainer = onTertiaryContainerLightHighContrast,
    error = errorLightHighContrast,
    onError = onErrorLightHighContrast,
    errorContainer = errorContainerLightHighContrast,
    onErrorContainer = onErrorContainerLightHighContrast,
    background = backgroundLightHighContrast,
    onBackground = onBackgroundLightHighContrast,
    surface = surfaceLightHighContrast,
    onSurface = onSurfaceLightHighContrast,
    surfaceVariant = surfaceVariantLightHighContrast,
    onSurfaceVariant = onSurfaceVariantLightHighContrast,
    outline = outlineLightHighContrast,
    outlineVariant = outlineVariantLightHighContrast,
    scrim = scrimLightHighContrast,
    inverseSurface = inverseSurfaceLightHighContrast,
    inverseOnSurface = inverseOnSurfaceLightHighContrast,
    inversePrimary = inversePrimaryLightHighContrast,
    surfaceDim = surfaceDimLightHighContrast,
    surfaceBright = surfaceBrightLightHighContrast,
    surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = surfaceContainerLowLightHighContrast,
    surfaceContainer = surfaceContainerLightHighContrast,
    surfaceContainerHigh = surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
)

private val darkStandardContrastColorScheme = darkColorScheme(
    primary = primaryDarkStandardContrast,
    onPrimary = onPrimaryDarkStandardContrast,
    primaryContainer = primaryContainerDarkStandardContrast,
    onPrimaryContainer = onPrimaryContainerDarkStandardContrast,
    secondary = secondaryDarkStandardContrast,
    onSecondary = onSecondaryDarkStandardContrast,
    secondaryContainer = secondaryContainerDarkStandardContrast,
    onSecondaryContainer = onSecondaryContainerDarkStandardContrast,
    tertiary = tertiaryDarkStandardContrast,
    onTertiary = onTertiaryDarkStandardContrast,
    tertiaryContainer = tertiaryContainerDarkStandardContrast,
    onTertiaryContainer = onTertiaryContainerDarkStandardContrast,
    error = errorDarkStandardContrast,
    onError = onErrorDarkStandardContrast,
    errorContainer = errorContainerDarkStandardContrast,
    onErrorContainer = onErrorContainerDarkStandardContrast,
    background = backgroundDarkStandardContrast,
    onBackground = onBackgroundDarkStandardContrast,
    surface = surfaceDarkStandardContrast,
    onSurface = onSurfaceDarkStandardContrast,
    surfaceVariant = surfaceVariantDarkStandardContrast,
    onSurfaceVariant = onSurfaceVariantDarkStandardContrast,
    outline = outlineDarkStandardContrast,
    outlineVariant = outlineVariantDarkStandardContrast,
    scrim = scrimDarkStandardContrast,
    inverseSurface = inverseSurfaceDarkStandardContrast,
    inverseOnSurface = inverseOnSurfaceDarkStandardContrast,
    inversePrimary = inversePrimaryDarkStandardContrast,
    surfaceDim = surfaceDimDarkStandardContrast,
    surfaceBright = surfaceBrightDarkStandardContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkStandardContrast,
    surfaceContainerLow = surfaceContainerLowDarkStandardContrast,
    surfaceContainer = surfaceContainerDarkStandardContrast,
    surfaceContainerHigh = surfaceContainerHighDarkStandardContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkStandardContrast,
)

private val darkMediumContrastColorScheme = darkColorScheme(
    primary = primaryDarkMediumContrast,
    onPrimary = onPrimaryDarkMediumContrast,
    primaryContainer = primaryContainerDarkMediumContrast,
    onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
    secondary = secondaryDarkMediumContrast,
    onSecondary = onSecondaryDarkMediumContrast,
    secondaryContainer = secondaryContainerDarkMediumContrast,
    onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
    tertiary = tertiaryDarkMediumContrast,
    onTertiary = onTertiaryDarkMediumContrast,
    tertiaryContainer = tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
    error = errorDarkMediumContrast,
    onError = onErrorDarkMediumContrast,
    errorContainer = errorContainerDarkMediumContrast,
    onErrorContainer = onErrorContainerDarkMediumContrast,
    background = backgroundDarkMediumContrast,
    onBackground = onBackgroundDarkMediumContrast,
    surface = surfaceDarkMediumContrast,
    onSurface = onSurfaceDarkMediumContrast,
    surfaceVariant = surfaceVariantDarkMediumContrast,
    onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
    outline = outlineDarkMediumContrast,
    outlineVariant = outlineVariantDarkMediumContrast,
    scrim = scrimDarkMediumContrast,
    inverseSurface = inverseSurfaceDarkMediumContrast,
    inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
    inversePrimary = inversePrimaryDarkMediumContrast,
    surfaceDim = surfaceDimDarkMediumContrast,
    surfaceBright = surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
    surfaceContainer = surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
)

private val darkHighContrastColorScheme = darkColorScheme(
    primary = primaryDarkHighContrast,
    onPrimary = onPrimaryDarkHighContrast,
    primaryContainer = primaryContainerDarkHighContrast,
    onPrimaryContainer = onPrimaryContainerDarkHighContrast,
    secondary = secondaryDarkHighContrast,
    onSecondary = onSecondaryDarkHighContrast,
    secondaryContainer = secondaryContainerDarkHighContrast,
    onSecondaryContainer = onSecondaryContainerDarkHighContrast,
    tertiary = tertiaryDarkHighContrast,
    onTertiary = onTertiaryDarkHighContrast,
    tertiaryContainer = tertiaryContainerDarkHighContrast,
    onTertiaryContainer = onTertiaryContainerDarkHighContrast,
    error = errorDarkHighContrast,
    onError = onErrorDarkHighContrast,
    errorContainer = errorContainerDarkHighContrast,
    onErrorContainer = onErrorContainerDarkHighContrast,
    background = backgroundDarkHighContrast,
    onBackground = onBackgroundDarkHighContrast,
    surface = surfaceDarkHighContrast,
    onSurface = onSurfaceDarkHighContrast,
    surfaceVariant = surfaceVariantDarkHighContrast,
    onSurfaceVariant = onSurfaceVariantDarkHighContrast,
    outline = outlineDarkHighContrast,
    outlineVariant = outlineVariantDarkHighContrast,
    scrim = scrimDarkHighContrast,
    inverseSurface = inverseSurfaceDarkHighContrast,
    inverseOnSurface = inverseOnSurfaceDarkHighContrast,
    inversePrimary = inversePrimaryDarkHighContrast,
    surfaceDim = surfaceDimDarkHighContrast,
    surfaceBright = surfaceBrightDarkHighContrast,
    surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = surfaceContainerLowDarkHighContrast,
    surfaceContainer = surfaceContainerDarkHighContrast,
    surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
)

internal fun getColorScheme(
    isDarkTheme: Boolean,
    contrast: CoreSettingsContrast,
): ColorScheme {
    return if (isDarkTheme) {
        when (contrast) {
            CoreSettingsContrast.STANDARD -> darkStandardContrastColorScheme
            CoreSettingsContrast.MEDIUM -> darkMediumContrastColorScheme
            CoreSettingsContrast.HIGH -> darkHighContrastColorScheme
        }
    } else {
        when (contrast) {
            CoreSettingsContrast.STANDARD -> lightStandardContrastColorScheme
            CoreSettingsContrast.MEDIUM -> lightMediumContrastColorScheme
            CoreSettingsContrast.HIGH -> lightHighContrastColorScheme
        }
    }
}
