name: Build
"on":
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: null
env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true
    -Dorg.gradle.caching=true
jobs:
  code-quality-detekt-main-desktop:
    name: Code quality detekt Main Desktop
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Gradle setup
      uses: ./.github/actions/gradle-setup
    - name: Check detekt Main Desktop
      run: ./gradlew detektMainDesktop --continue
    - name: Merge detekt reports
      if: always()
      run: ./gradlew detektReportMerge
    - name: Upload detekt report
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: build/reports/detekt/detekt.sarif
  code-quality-spotless:
    name: Code quality spotless
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Gradle setup
      uses: ./.github/actions/gradle-setup
    - name: Check spotless
      run: ./gradlew spotlessCheck --continue
  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
    - code-quality-detekt-main-desktop
    - code-quality-spotless
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Gradle setup
      uses: ./.github/actions/gradle-setup
    - name: Run unit tests
      run: ./gradlew desktopTest
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: test-reports
        path: '**/build/reports/tests/'
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Gradle setup
      uses: ./.github/actions/gradle-setup
    - name: Build Android debug APK
      run: ./gradlew :app:androidApp:assembleDebug
  build-desktop-linux:
    name: Build Desktop Linux
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Gradle setup
      uses: ./.github/actions/gradle-setup
    - name: Build Linux DEB
      run: ./gradlew :app:desktopApp:packageDeb
  build-desktop-macos:
    name: Build Desktop macOS
    runs-on: macos-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Gradle setup
      uses: ./.github/actions/gradle-setup
    - name: Build macOS DMG
      run: ./gradlew :app:desktopApp:packageDmg
  build-desktop-windows:
    name: Build Desktop Windows
    runs-on: windows-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5.0.0
    - name: Build Windows MSI
      run: ./gradlew :app:desktopApp:packageMsi
  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Gradle setup
      uses: ./.github/actions/gradle-setup
    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer
    - name: Build iOS simulator app
      run: |
        xcodebuild build \
        -project app/iosApp/iosApp.xcodeproj \
        -configuration Debug \
        -scheme "app [ios]" \
        -sdk iphonesimulator \
        -arch arm64 \
        -derivedDataPath ./build \
        -verbose
  build-web-js:
    name: Build Web Js
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Gradle setup
      uses: ./.github/actions/gradle-setup
    - name: Build Wasm distribution
      run: ./gradlew :app:webApp:jsBrowserDistribution
  build-web-wasm:
    name: Build Web Wasm
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Gradle setup
      uses: ./.github/actions/gradle-setup
    - name: Build Wasm distribution
      run: ./gradlew :app:webApp:wasmJsBrowserDistribution
